In [ ]:
import numpy as np
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x.shape)
print(v.shape)
y = x + v  # Add v to each row of x using broadcasting
# print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

In [4]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([1,2,3])
y = np.reshape(y, (3,1))
x / y

array([[ 1.        ,  2.        ],
       [ 1.5       ,  2.        ],
       [ 1.66666667,  2.        ]])